services:
  app_a1:
    build:
      context: ./appA
      dockerfile: Dockerfile
    container_name: app_a1_container
    ports:
      - "5001:5000"  # ホストの5001をコンテナの5001にマッピング（ホストマシン:コンテナ）
    volumes:
      - ./appA:/usr/src/app
    environment:
      - ENV_VAR="app_a1"
    command: python appA_main.py  # コンテナ起動時に実行するコマンド

  app_a2:
    build:
      context: ./appA
      dockerfile: Dockerfile
    container_name: app_a2_container
    ports:
      - "5002:5000"  # ホストの5002をコンテナの5001にマッピング（ホストマシン:コンテナ）
    volumes:
      - ./appA:/usr/src/app
    environment:
      - ENV_VAR="app_a2"
    command: python appA_main.py  # コンテナ起動時に実行するコマンド

  app_b1:
    build:
      context: ./appB
      dockerfile: Dockerfile
    container_name: app_b1_container
    ports:
      - "6001:6000"  # ホストの5002をコンテナの5002にマッピング
    volumes:
      - ./appB:/usr/src/app
    environment:
      - ENV_VAR="app_b1"
    command: python appB_main.py
